// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SUA-CV7-NcG5erJwb-oLrtgLqovmNnw',
    appId: '1:683840768764:web:a5b27975286a2826b0e579',
    messagingSenderId: '683840768764',
    projectId: 'habithub-5e620',
    authDomain: 'habithub-5e620.firebaseapp.com',
    storageBucket: 'habithub-5e620.firebasestorage.app',
    measurementId: 'G-5HFP425WE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxiBQO_2g_f5Io1BH_ORB7lXwXbfjR1ek',
    appId: '1:683840768764:android:93498929155b05e0b0e579',
    messagingSenderId: '683840768764',
    projectId: 'habithub-5e620',
    storageBucket: 'habithub-5e620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUuwODZSSObmq7TqQbVWAgG55F4Jr06sw',
    appId: '1:683840768764:ios:a46b4d133d21fe5db0e579',
    messagingSenderId: '683840768764',
    projectId: 'habithub-5e620',
    storageBucket: 'habithub-5e620.firebasestorage.app',
    iosBundleId: 'com.example.habithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUuwODZSSObmq7TqQbVWAgG55F4Jr06sw',
    appId: '1:683840768764:ios:a46b4d133d21fe5db0e579',
    messagingSenderId: '683840768764',
    projectId: 'habithub-5e620',
    storageBucket: 'habithub-5e620.firebasestorage.app',
    iosBundleId: 'com.example.habithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SUA-CV7-NcG5erJwb-oLrtgLqovmNnw',
    appId: '1:683840768764:web:1125d3fdd605c46db0e579',
    messagingSenderId: '683840768764',
    projectId: 'habithub-5e620',
    authDomain: 'habithub-5e620.firebaseapp.com',
    storageBucket: 'habithub-5e620.firebasestorage.app',
    measurementId: 'G-ZH3638NR5Y',
  );
}
